CREATE TABLE addressbook (
   id int unsigned NOT NULL auto_increment,
   title varchar(255) NOT NULL,
   firstname varchar(255) NOT NULL,
   firstname2 varchar(255) NOT NULL,
   lastname varchar(255) NOT NULL,
   suffix varchar(255) NOT NULL,
   nickname varchar(255) NOT NULL,
   jobtitle varchar(255) NOT NULL,
   department varchar(255) NOT NULL,
   organization varchar(255) NOT NULL,
   company boolean NOT NULL default 0,
   birthdate date NOT NULL default '0000-00-00',
   image mediumblob NOT NULL,
   note text NOT NULL,
   addresses text NOT NULL,
   emails text NOT NULL,
   phones text NOT NULL,
   chathandles text NOT NULL,
   relatednames text NOT NULL,
   urls text NOT NULL,
   creationdate datetime NOT NULL default '0000-00-00 00:00:00',
   modificationdate datetime NOT NULL default '0000-00-00 00:00:00',
   PRIMARY KEY (id)
);

